wtf:
  colors:
    border:
      focusable: darkslateblue
      focused: orange
      normal: gray
  grid:
    columns: [35, 35, 35, 35, 90]
    rows: [11, 4, 10, 10, 3, 10,10]
  refreshInterval: 1
  mods:
    timeshift:
      title: "Backup Status"
      args: []
      cmd: "/home/pim/.config/wtf/timeshift-last.sh"
      enabled: true
      position:
        top: 0
        left: 0
        height: 1
        width: 2
      refreshInterval: 30
      type: cmdrunner
    docker:
      title: docker
      args: ["ps","--format", "table {{.Names}}\t{{.Status}}"]
      cmd: docker
      enabled: true
      position:
        top: 0
        left: 2
        height: 1
        width: 1
      refreshInterval: 600
      type: cmdrunner
    monitoring:
      title: "Diverse systemen"
      args: []
      cmd: "/home/pim/.config/wtf/ssh-monitoring.sh"
      enabled: true
      position:
        top: 1
        left: 0
        height: 1
        width: 3
      refreshInterval: 30
      type: cmdrunner
    letsencrypt:
      title: "LetsEnctypt Problems"
      args: ['letsencryptproblems']
      cmd: "rake"
      enabled: true
      position:
        top: 2
        left: 0
        height: 1
        width: 3
      refreshInterval: 86400
      type: cmdrunner
    letsencrypt2:
      title: "LetsEnctypt Almost"
      args: ['letsencryptalmost']
      cmd: "rake"
      enabled: true
      position:
        top: 3
        left: 0
        height: 1
        width: 3
      refreshInterval: 86400
      type: cmdrunner
    uptime:
      args: [""]
      cmd: "uptime"
      enabled: true
      position:
        top: 4
        left: 0
        height: 1
        width: 3
      refreshInterval: 30
      type: cmdrunner
    ipinfo:
      colors:
        name: "lightblue"
        value: "white"
      enabled: true
      position:
        top: 5
        left: 0
        height: 1
        width: 2
      refreshInterval: 150
    digitalclock:
      color: orange
      enabled: true
      font: bigfont
      hourFormat: 12
      position:
        top: 5
        left: 2
        height: 1
        width: 1
      refreshInterval: 1
      title: "big clock"
      type: "digitalclock"
    cryptolive:
      enabled: true
      position:
        top: 6
        left: 0
        height: 1
        width: 1
      updateInterval: 15
      currencies:
        DOGE:
          displayName: DOGE
          to:
            - EUR
      colors:
        from:
          name: coral
          displayName: grey
        to:
          name: white
          price: green
        top:
          from:
            name: grey
            displayName: coral
          to:
            name: red
            field: white
            value: green
