# Use tall and fullscreen layouts
#layouts:
#    - tall
#    - fullscreen
#    - tall-right
#    - wide
#    - two-pane
#    - 3column-left
#    - middle-wide
#    - 3column-right
#    - 4column-left
#    - 4column-right
#    - column
#    - row
#    - floating
#    - widescreen-tall
#    - widescreen-tall-right
#    - bsp

# Add "command" to the default mods
#mod1:
#    - option
#    - shift
#    - command
#mod2:
#    - option
#    - shift
#    - control
#    - command
#
## Modify the amethyst relaunch to use x and not z
#relaunch-amethyst:
#    mod: mod2
#    key: x

# Enable focus-follows-mouse
#mouse-follows-focus: false
#focus-follows-mouse: true

# Add 10px margin between windows
window-margins: true
window-margin-size: 11
